"""Add token tracking fields to conversation_log

Revision ID: 0540b4a02149
Revises: d3e271dd7b84
Create Date: 2025-10-29 00:20:18.565923

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0540b4a02149'
down_revision = 'd3e271dd7b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_log', sa.Column('input_tokens', sa.Integer(), nullable=False))
    op.add_column('conversation_log', sa.Column('output_tokens', sa.Integer(), nullable=False))
    op.add_column('conversation_log', sa.Column('total_tokens', sa.Integer(), nullable=False))
    op.add_column('conversation_log', sa.Column('token_details', sa.JSON(), nullable=True))
    op.add_column('conversation_log', sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('conversation_log', sa.Column('estimated_cost_usd', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_log', 'estimated_cost_usd')
    op.drop_column('conversation_log', 'model_used')
    op.drop_column('conversation_log', 'token_details')
    op.drop_column('conversation_log', 'total_tokens')
    op.drop_column('conversation_log', 'output_tokens')
    op.drop_column('conversation_log', 'input_tokens')
    # ### end Alembic commands ###
