"""Add Agent and Block models - single table design

Revision ID: 2aa9cd8c58de
Revises: 1a31ce608336
Create Date: 2025-10-25 16:51:12.408431

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2aa9cd8c58de'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blocks', sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blocks', sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blocks', sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blocks', sa.Column('tone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blocks', sa.Column('languages', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blocks', sa.Column('use_emojis', sa.Boolean(), nullable=True))
    op.add_column('blocks', sa.Column('emoji_frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blocks', sa.Column('response_length', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blocks', sa.Column('constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blocks', sa.Column('guidelines', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blocks', sa.Column('example_conversations', sa.JSON(), nullable=True))
    op.add_column('blocks', sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blocks', sa.Column('config', sa.JSON(), nullable=True))
    op.add_column('blocks', sa.Column('integration_id', sa.Integer(), nullable=True))
    op.add_column('blocks', sa.Column('trigger_conditions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blocks', sa.Column('requires_confirmation', sa.Boolean(), nullable=True))
    op.add_column('blocks', sa.Column('metadata_', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'metadata_')
    op.drop_column('blocks', 'requires_confirmation')
    op.drop_column('blocks', 'trigger_conditions')
    op.drop_column('blocks', 'integration_id')
    op.drop_column('blocks', 'config')
    op.drop_column('blocks', 'action_type')
    op.drop_column('blocks', 'example_conversations')
    op.drop_column('blocks', 'guidelines')
    op.drop_column('blocks', 'constraints')
    op.drop_column('blocks', 'response_length')
    op.drop_column('blocks', 'emoji_frequency')
    op.drop_column('blocks', 'use_emojis')
    op.drop_column('blocks', 'languages')
    op.drop_column('blocks', 'tone')
    op.drop_column('blocks', 'file_type')
    op.drop_column('blocks', 'file_path')
    op.drop_column('blocks', 'content_type')
    op.drop_column('blocks', 'content')
    # ### end Alembic commands ###
