"""Add tools field to agent model

Revision ID: 9fbbb35737b8
Revises: f0fe9b8ca32e
Create Date: 2025-11-02 03:28:56.343259

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fbbb35737b8'
down_revision = 'f0fe9b8ca32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('tools', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'tools')
    # ### end Alembic commands ###
