"""add custom icon color tag to neo_agents

Revision ID: aebab462771a
Revises: contact_fields_001
Create Date: 2025-11-26 23:25:33.970333

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aebab462771a'
down_revision = 'contact_fields_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blocks_agent_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_block_type'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('mem0migrations_hnsw_idx'), table_name='mem0migrations', postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('mem0migrations')
    op.drop_table('item')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.drop_index(op.f('memories_hnsw_idx'), table_name='memories', postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('memories')
    op.drop_table('pipeline_columns')
    op.drop_table('checkpoint_migrations')
    op.drop_index(op.f('ix_agent_field_configs_agent_id'), table_name='agent_field_configs')
    op.drop_index(op.f('ix_agent_field_configs_field_id'), table_name='agent_field_configs')
    op.drop_table('agent_field_configs')
    op.drop_index(op.f('ix_pipeline_cards_column_id'), table_name='pipeline_cards')
    op.drop_index(op.f('ix_pipeline_cards_contact_id'), table_name='pipeline_cards')
    op.drop_table('pipeline_cards')
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_pipeline_stage'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_index(op.f('ix_contact_fields_key'), table_name='contact_fields')
    op.drop_table('contact_fields')
    op.drop_constraint(op.f('uq_booking_configs_entity'), 'booking_configs', type_='unique')
    op.drop_constraint(op.f('booking_configs_entity_id_fkey'), 'booking_configs', type_='foreignkey')
    op.create_foreign_key(None, 'booking_configs', 'entities', ['entity_id'], ['id'])
    op.drop_index(op.f('ix_bookings_booking_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_professional_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_service_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_constraint(op.f('chunk_labels_chunk_id_fkey'), 'chunk_labels', type_='foreignkey')
    op.drop_constraint(op.f('chunk_labels_label_id_fkey'), 'chunk_labels', type_='foreignkey')
    op.create_foreign_key(None, 'chunk_labels', 'knowledge_base', ['chunk_id'], ['id'])
    op.create_foreign_key(None, 'chunk_labels', 'labels', ['label_id'], ['id'])
    op.alter_column('conversation_log', 'intent',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('conversation_log', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(op.f('entity_links_source_entity_id_fkey'), 'entity_links', type_='foreignkey')
    op.drop_constraint(op.f('entity_links_target_entity_id_fkey'), 'entity_links', type_='foreignkey')
    op.create_foreign_key(None, 'entity_links', 'entities', ['target_entity_id'], ['id'])
    op.create_foreign_key(None, 'entity_links', 'entities', ['source_entity_id'], ['id'])
    op.drop_constraint(op.f('uq_inventory_entity'), 'inventory', type_='unique')
    op.drop_constraint(op.f('inventory_entity_id_fkey'), 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'entities', ['entity_id'], ['id'])
    op.alter_column('knowledge_base', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('knowledge_base', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_knowledge_base_labels'), table_name='knowledge_base', postgresql_using='gin')
    op.drop_constraint(op.f('fk_knowledge_base_block_id'), 'knowledge_base', type_='foreignkey')
    op.drop_column('knowledge_base', 'block_id')
    op.drop_constraint(op.f('uq_labels_user_name'), 'labels', type_='unique')
    op.add_column('neo_agents', sa.Column('custom_icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('neo_agents', sa.Column('custom_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('neo_agents', sa.Column('custom_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('schedules', 'entity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('schedules', 'professional_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_schedules_day_of_week'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_professional_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_specific_date'), table_name='schedules')
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_schedules_specific_date'), 'schedules', ['specific_date'], unique=False)
    op.create_index(op.f('ix_schedules_professional_id'), 'schedules', ['professional_id'], unique=False)
    op.create_index(op.f('ix_schedules_day_of_week'), 'schedules', ['day_of_week'], unique=False)
    op.alter_column('schedules', 'professional_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('schedules', 'entity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('neo_agents', 'custom_tag')
    op.drop_column('neo_agents', 'custom_color')
    op.drop_column('neo_agents', 'custom_icon')
    op.create_unique_constraint(op.f('uq_labels_user_name'), 'labels', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    op.add_column('knowledge_base', sa.Column('block_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_knowledge_base_block_id'), 'knowledge_base', 'blocks', ['block_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_knowledge_base_labels'), 'knowledge_base', ['labels'], unique=False, postgresql_using='gin')
    op.alter_column('knowledge_base', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('knowledge_base', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_entity_id_fkey'), 'inventory', 'entities', ['entity_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_inventory_entity'), 'inventory', ['entity_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'entity_links', type_='foreignkey')
    op.drop_constraint(None, 'entity_links', type_='foreignkey')
    op.create_foreign_key(op.f('entity_links_target_entity_id_fkey'), 'entity_links', 'entities', ['target_entity_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('entity_links_source_entity_id_fkey'), 'entity_links', 'entities', ['source_entity_id'], ['id'], ondelete='CASCADE')
    op.alter_column('conversation_log', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('conversation_log', 'intent',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'chunk_labels', type_='foreignkey')
    op.drop_constraint(None, 'chunk_labels', type_='foreignkey')
    op.create_foreign_key(op.f('chunk_labels_label_id_fkey'), 'chunk_labels', 'labels', ['label_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('chunk_labels_chunk_id_fkey'), 'chunk_labels', 'knowledge_base', ['chunk_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_service_id'), 'bookings', ['service_id'], unique=False)
    op.create_index(op.f('ix_bookings_professional_id'), 'bookings', ['professional_id'], unique=False)
    op.create_index(op.f('ix_bookings_booking_date'), 'bookings', ['booking_date'], unique=False)
    op.drop_constraint(None, 'booking_configs', type_='foreignkey')
    op.create_foreign_key(op.f('booking_configs_entity_id_fkey'), 'booking_configs', 'entities', ['entity_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_booking_configs_entity'), 'booking_configs', ['entity_id'], postgresql_nulls_not_distinct=False)
    op.create_table('contact_fields',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('contact_fields_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('field_type', sa.VARCHAR(), server_default=sa.text("'text'::character varying"), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('show_in_list', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('show_in_card', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='contact_fields_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_contact_fields_key'), 'contact_fields', ['key'], unique=False)
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('contacts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_agent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('pipeline_stage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_interaction_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_agent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('conversation_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='contacts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_contacts_pipeline_stage'), 'contacts', ['pipeline_stage'], unique=False)
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=False)
    op.create_table('pipeline_cards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('column_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('labels', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_activity_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('moved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['pipeline_columns.id'], name=op.f('pipeline_cards_column_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('pipeline_cards_contact_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pipeline_cards_pkey'))
    )
    op.create_index(op.f('ix_pipeline_cards_contact_id'), 'pipeline_cards', ['contact_id'], unique=False)
    op.create_index(op.f('ix_pipeline_cards_column_id'), 'pipeline_cards', ['column_id'], unique=False)
    op.create_table('agent_field_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('necessity', sa.VARCHAR(), server_default=sa.text("'optional'::character varying"), autoincrement=False, nullable=False),
    sa.Column('collection_hint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('required_for_tools', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['contact_fields.id'], name=op.f('agent_field_configs_field_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_field_configs_pkey'))
    )
    op.create_index(op.f('ix_agent_field_configs_field_id'), 'agent_field_configs', ['field_id'], unique=False)
    op.create_index(op.f('ix_agent_field_configs_agent_id'), 'agent_field_configs', ['agent_id'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('pipeline_columns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pipeline_columns_pkey'))
    )
    op.create_table('memories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('memories_pkey'))
    )
    op.create_index(op.f('memories_hnsw_idx'), 'memories', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('item_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('item_pkey'))
    )
    op.create_table('mem0migrations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mem0migrations_pkey'))
    )
    op.create_index(op.f('mem0migrations_hnsw_idx'), 'mem0migrations', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_table('blocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('block_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('languages', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('use_emojis', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('emoji_frequency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('response_length', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('constraints', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('guidelines', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('example_conversations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('integration_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trigger_conditions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('requires_confirmation', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name=op.f('blocks_agent_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('blocks_pkey'))
    )
    op.create_index(op.f('ix_blocks_block_type'), 'blocks', ['block_type'], unique=False)
    op.create_index(op.f('ix_blocks_agent_id'), 'blocks', ['agent_id'], unique=False)
    # ### end Alembic commands ###
