"""Add conversation_log table for analytics

Revision ID: d3e271dd7b84
Revises: 54c3049ac1e8
Create Date: 2025-10-29 00:08:42.611623

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd3e271dd7b84'
down_revision = '54c3049ac1e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('agent_timings', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_chars', sa.Integer(), nullable=False),
    sa.Column('output_chars', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_log_agent_id'), 'conversation_log', ['agent_id'], unique=False)
    op.create_index(op.f('ix_conversation_log_created_at'), 'conversation_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_log_customer_id'), 'conversation_log', ['customer_id'], unique=False)
    op.create_index(op.f('ix_conversation_log_workflow_id'), 'conversation_log', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_log_workflow_id'), table_name='conversation_log')
    op.drop_index(op.f('ix_conversation_log_customer_id'), table_name='conversation_log')
    op.drop_index(op.f('ix_conversation_log_created_at'), table_name='conversation_log')
    op.drop_index(op.f('ix_conversation_log_agent_id'), table_name='conversation_log')
    op.drop_table('conversation_log')
    # ### end Alembic commands ###
