"""Add soft delete to blocks

Revision ID: e33d6a2ccbb0
Revises: c923cc5fc03b
Create Date: 2025-10-29 19:31:52.872224

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e33d6a2ccbb0'
down_revision = 'c923cc5fc03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add deleted_at column to blocks table (removed other unsafe operations)
    op.add_column('blocks', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'deleted_at')
    # ### end Alembic commands ###
